name: CDK CI-CD

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
      types: [published]

jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event.action }}"
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci --no-progress --ignore-scripts=false
      
      - name: Lint
        run: 'npm run lint'

  Test-Unit:
    name: Test - Unit
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event.action }}"
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci --no-progress --ignore-scripts=false
      
      - name: Lint
        run: 'npm run lint'

  Test-e2e:
    name: Test - End to End
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event.action }}"
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci --no-progress --ignore-scripts=false
      
      - name: Lint
        run: 'npm run lint'

  Test-Infrastructure:
    name: Test - Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event.action }}"
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci --no-progress --ignore-scripts=false
      
      - name: Lint
        run: 'npm run lint'          

  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event.action }}"
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci --no-progress --ignore-scripts=false
      
      - name: Build
        run: 'npm run build'

      - name: CDK Synth
        run: 'npm run cdk -- synth -c siteSubDomain=cdk -c region=us-east-1'
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cdk.out
          path: /home/runner/work/cdk-webstack/cdk-webstack/cdk.out

  deploy-to-dev:
    name: Deploy to Development
    if: (github.event_name == 'release' && 1 != 1)
    runs-on: ubuntu-latest
    needs: [Lint, Test-Unit, Test-e2e, Test-Infrastructure, Build]
    environment:
      name: Development
      url: 'https://cdk.ahearth.com'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci --no-progress --ignore-scripts=false

      - name: CDK Deploy
        run: 'npm run cdk -- deploy -c siteSubDomain=cdk -c region=us-east-1 --require-approval never'

  deploy-to-stage:
    name: Deploy to Staging
    if: (github.event_name == 'release' && 1 != 1)
    runs-on: ubuntu-latest
    needs: [Lint, Test-Unit, Test-e2e, Test-Infrastructure, Build]
    environment:
      name: Staging
      url: 'https://cdk.ahearth.com'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci --no-progress --ignore-scripts=false

      - name: CDK Deploy
        run: 'npm run cdk -- deploy -c siteSubDomain=cdk -c region=us-east-1 --require-approval never'        

  deploy-to-production:
    name: Deploy to Production
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [Lint, Test-Unit, Test-e2e, Test-Infrastructure, Build]
    environment:
      name: Production
      url: 'https://cdk.ahearth.com'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci --no-progress --ignore-scripts=false

      - name: CDK Deploy
        run: 'npm run cdk -- deploy -c siteSubDomain=cdk -c region=us-east-1 --require-approval never'
